name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile CSS and JS
        run: |
          npm install
          npm run prod

      - name: Configure PHP 7.3
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.3
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, JSON, tokenizer, xml
